# Deployment Section
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice                # Name of the deployment
spec:
  selector:
    matchLabels:
      app: productcatalogservice             # Label selector for pods
  template:
    metadata:
      labels:
        app: productcatalogservice           # Label assigned to pods
    spec:
      containers:
      - name: service          # Container name
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.8.0         # Docker image URL
        ports:
        - containerPort: 3550  # Port the app listens on
        env:
        - name: PORT
          value: "3550"

# Service Section
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice                # Service name
spec:
  type: ClusterIP          # Service type (ClusterIP, NodePort, LoadBalancer)
  selector:
    app: productcatalogservice               # Label selector for pods
  ports:
  - port: 3550             # Service port (accessible internally)
    targetPort: 3550       # Pod port (where the app runs)
