# Deployment Section
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice                # Name of the deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: shippingservice             # Label selector for pods
  template:
    metadata:
      labels:
        app: shippingservice           # Label assigned to pods
    spec:
      containers:
      - name: service          # Container name
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.8.0         # Docker image URL
        ports:
        - containerPort: 50051  # Port the app listens on
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 50051
          periodSeconds: 5
        readinessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: 50051
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m       # 0.1 CPU core
            memory: 128Mi   # 128 MiB of memory
          limits:
            cpu: 250m       # 0.25 CPU core
            memory: 256Mi   # 256 MiB of memory
    
          
# Service Section
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice                # Service name
spec:
  type: ClusterIP          # Service type (ClusterIP, NodePort, LoadBalancer)
  selector:
    app: shippingservice               # Label selector for pods
  ports:
  - protocol: TCP
    port: 50051             # Service port (accessible internally)
    targetPort: 50051       # Pod port (where the app runs)

