# Deployment Section
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice                # Name of the deployment
spec:
  selector:
    matchLabels:
      app: shippingservice             # Label selector for pods
  template:
    metadata:
      labels:
        app: shippingservice           # Label assigned to pods
    spec:
      containers:
      - name: service          # Container name
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.8.0         # Docker image URL
        ports:
        - containerPort: 50051  # Port the app listens on

# Service Section
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice                # Service name
spec:
  type: ClusterIP          # Service type (ClusterIP, NodePort, LoadBalancer)
  selector:
    app: shippingservice               # Label selector for pods
  ports:
  - protocol: TCP
    port: 50051             # Service port (accessible internally)
    targetPort: 50051       # Pod port (where the app runs)

