appName: cartservice
appImage: gcr.io/google-samples/microservices-demo/cartservice
appVersion: v0.8.0
appReplicas: 1
containerPort: 7070
containerEnvVars:
  - key: PORT
    value: "7070"
  - key: REDIS_ADDR
    value: "redis-cart:6379"    

servicePort: 7070
serviceType: ClusterIP

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: cartservice.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
