appName: currencyservice
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.8.0
appReplicas: 1
containerPort: 7000
containerEnvVars:
  - key: PORT
    value: "7000"
  - key: DISABLE_PROFILER
    value: "1"

servicePort: 7000
serviceType: ClusterIP

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: currencyservice.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
