appName: emailservice
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.8.0
appReplicas: 1
containerPort: 8080
containerEnvVars:
  - key: PORT
    value: "8080"

servicePort: 8080
serviceType: ClusterIP

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: emailservice.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

