appName: frontend
appImage: gcr.io/google-samples/microservices-demo/frontend
appVersion: v0.8.0
appReplicas: 1
containerPort: 8080
containerEnvVars:
  - key: PORT
    value: "8080"
  - key: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - key: CURRENCY_SERVICE_ADDR
    value: "currencyservice:7000"
  - key: CART_SERVICE_ADDR
    value: "cartservice:7070"
  - key: RECOMMENDATION_SERVICE_ADDR
    value: "recommendationservice:8080"
  - key: SHIPPING_SERVICE_ADDR
    value: "shippingservice:50051"
  - key: CHECKOUT_SERVICE_ADDR
    value: "checkoutservice:5050"
  - key: AD_SERVICE_ADDR
    value: "adservice:9555"


servicePort: 8080
serviceType: LoadBalancer

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: frontend.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
