appName: productcatalogservice
appImage: gcr.io/google-samples/microservices-demo/productcatalogservice
appVersion: v0.8.0
appReplicas: 1
containerPort: 3550
containerEnvVars:
  - key: PORT
    value: "3550"

servicePort: 3550
serviceType: ClusterIP

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: productcatalogservice.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
