appName: shippingservice
appImage: gcr.io/google-samples/microservices-demo/shippingservice
appVersion: v0.8.0
appReplicas: 1
containerPort: 50051
containerEnvVars:
  - key: PORT
    value: "50051"

servicePort: 8080
serviceType: ClusterIP

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: shippingservice.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
