appName: redis
appImage: redis
appVersion: alpine
appReplicas: 1
containerPort: 6379
volumeName: redis-data
containerMountPath: /data

service:
  port: 6379
  type: ClusterIP

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: emailservice.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

